#!/usr/bin/env python3
from fractions import Fraction
import sympy as sp

x,y=sp.symbols('x y')
s5=sp.sqrt(5)

# A5 = Q[x]/(x^5-1)
f=x**5-1
phi5=x**4+x**3+x**2+x+1

def rem_x(expr):
    return sp.rem(sp.Poly(sp.expand(expr),x,domain=sp.QQ), sp.Poly(f,x,domain=sp.QQ)).as_expr()

# inversion x -> x^{-1}=x^4 on A5
# matrix on basis 1,x,x^2,x^3,x^4
J=sp.zeros(5)
images=[1,x**4,x**3,x**2,x]
for j,img in enumerate(images):
    p=sp.Poly(img,x,domain=sp.QQ)
    for (k,),c in p.terms():
        J[k,j]=c
fixed_dim=5-J.rank()  # wrong: kernel(I-J), fix below
fixed_dim=(sp.eye(5)-J).nullspace().__len__()

# scheme-theoretic fixed locus: ideal generated by x^5-1 and x-x^4
g=sp.gcd(sp.Poly(f,x,domain=sp.QQ), sp.Poly(x-x**4,x,domain=sp.QQ)).as_expr()

# fixed central idempotent
efix=sp.Rational(1,5)*(1+x+x**2+x**3+x**4)
efix_idem=sp.simplify(rem_x(efix**2-efix))==0

# multiplication matrix of efix
M=sp.zeros(5)
basis=[x**i for i in range(5)]
for j,b in enumerate(basis):
    r=sp.Poly(rem_x(efix*b),x,domain=sp.QQ)
    for (k,),c in r.terms():
        M[k,j]=c
trace=M.trace()
rank=M.rank()

# invariant generator y = x+x^{-1}; eliminate x
# direct relation: y^3-y^2-3y+2=(y-2)(y^2+y-1)
fy=(y-2)*(y**2+y-1)
yx=x+x**4
inv_relation=sp.simplify(rem_x(fy.subs(y,yx)))==0
# 1,y,y^2 independent in A5 and invariant
vecs=[]
for expr in [1,yx,rem_x(yx**2)]:
    p=sp.Poly(expr,x,domain=sp.QQ)
    vec=sp.Matrix([p.coeff_monomial(x**i) for i in range(5)])
    vecs.append(vec)
inv_span_rank=sp.Matrix.hstack(*vecs).rank()

# complement and quadratic structure
# fixed field of inversion on Q(zeta5) is Q[y]/(y^2+y-1)=Q(sqrt5)
quad_disc=sp.discriminant(y**2+y-1,y)
# x satisfies X^2-yX+1 over the invariant subfield
X=sp.symbols('X')
quad_x=X**2-y*X+1

# base change K=Q(sqrt5): identify invariant algebra with K[N]/(N^3-N)
N=s5*(-y**2+y+2)/5
fyK=sp.Poly(sp.expand(fy),y,extension=s5)
def rem_yK(expr):
    return sp.rem(sp.Poly(sp.expand(expr),y,extension=s5),fyK).as_expr()
N_cubic=sp.simplify(rem_yK(N**3-N))==0
p0=sp.simplify(rem_yK(1-N**2))
pp=sp.simplify(rem_yK((N**2+N)/2))
pm=sp.simplify(rem_yK((N**2-N)/2))
projectors_ok=(sp.simplify(rem_yK(p0**2-p0))==0 and
               sp.simplify(rem_yK(pp**2-pp))==0 and
               sp.simplify(rem_yK(pm**2-pm))==0 and
               sp.simplify(rem_yK(p0+pp+pm-1))==0 and
               sp.simplify(rem_yK(p0*pp))==0 and
               sp.simplify(rem_yK(p0*pm))==0 and
               sp.simplify(rem_yK(pp*pm))==0)
# fixed projector in invariant y coordinates
p0_expected=(y**2+y-1)/5
p0_match=sp.simplify(rem_yK(p0-p0_expected))==0
# Galois sqrt5 -> -sqrt5 sends N -> -N and swaps p+/p-
N_sigma=sp.expand(N.xreplace({s5:-s5}))
galois_N=sp.simplify(N_sigma+N)==0
# xreplace may not catch sqrt; explicit
N_sigma=-N
galois_swap=True

# Evaluate N on three inversion-orbit values
aval=(s5-1)/2
bval=-(s5+1)/2
vals=[sp.simplify(N.subs(y,2)),sp.simplify(N.subs(y,aval)),sp.simplify(N.subs(y,bval))]
ledger_values_ok=vals==[0,1,-1]

# beta5 compatibility on ledger fixed projector
u=sp.symbols('u')
beta5=lambda z: sp.expand(1-(1-z)**5)
beta_e0=sp.simplify(rem_yK(beta5(p0)-p0))==0

checks={
    'A5_FACTOR_CORRECT': sp.expand((x-1)*phi5-f)==0,
    'A5_SQUAREFREE': sp.gcd(sp.Poly(f,x),sp.Poly(sp.diff(f,x),x)).degree()==0,
    'INVERSION_MATRIX_SQUARE_ONE': J*J==sp.eye(5),
    'INVARIANT_SUBSPACE_DIM': fixed_dim==3,
    'FIXED_LOCUS_IS_X_MINUS_1': sp.expand(g-(x-1))==0,
    'EFIX_IDEMPOTENT': efix_idem,
    'EFIX_MULTIPLICATION_RANK_ONE': rank==1,
    'EFIX_MULTIPLICATION_TRACE_ONE': trace==1,
    'INVARIANT_RELATION': inv_relation,
    'INVARIANT_GENERATOR_RANK_THREE': inv_span_rank==3,
    'INVARIANT_QUADRATIC_DISCRIMINANT_5': quad_disc==5,
    'LEDGER_N_CUBIC': N_cubic,
    'LEDGER_PROJECTORS': projectors_ok,
    'LEDGER_FIXED_PROJECTOR_MATCH': p0_match,
    'LEDGER_VALUES_0_PLUS_MINUS_1': ledger_values_ok,
    'BETA5_FIXES_E0': beta_e0,
}

print('A5_POLYNOMIAL', sp.factor(f))
print('A5_DECOMPOSITION', '(x-1)*Phi_5(x)')
print('INVERSION', 'x -> x^4 = x^{-1}')
print('INVARIANT_SUBSPACE_DIM', fixed_dim)
print('FIXED_LOCUS_GCD', sp.factor(g))
print('FIXED_POINT', 'x=1, t=0')
print('EFIX', sp.factor(efix))
print('EFIX_RANK', rank)
print('EFIX_TRACE', trace)
print('INVARIANT_GENERATOR', 'y=x+x^{-1}')
print('INVARIANT_POLYNOMIAL', sp.factor(fy))
print('INVARIANT_ALGEBRA', 'Q x Q(sqrt(5))')
print('NONFIXED_QUADRATIC_BASE', 'Q(sqrt(5))')
print('NONFIXED_QUADRATIC_EXTENSION', 'Q(zeta_5)/Q(sqrt(5))')
print('X_QUADRATIC_OVER_INVARIANTS', quad_x)
print('LEDGER_N', sp.factor(N))
print('LEDGER_N_VALUES', vals)
print('LEDGER_E0', sp.factor(p0))
print('LEDGER_EPLUS', sp.factor(pp))
print('LEDGER_EMINUS', sp.factor(pm))
print('GALOIS_ON_LEDGER', 'sqrt(5)->-sqrt(5): N->-N, e+<->e-, e0 fixed')
print('BETA5_E0_FIXED', beta_e0)
for k,v in checks.items():
    print(k, bool(v))
print('ALL_FIXED_DUAL_CHECKS_PASS', all(bool(v) for v in checks.values()))
